# Form implementation generated from reading ui file 'Martin/dialog_insert_unit.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 401, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 251))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_date = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_date.setObjectName("label_date")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_date)
        self.input_date = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.input_date.setObjectName("input_date")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.input_date)
        self.label_duration = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_duration.setObjectName("label_duration")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_duration)
        self.input_duration = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.input_duration.setObjectName("input_duration")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.input_duration)
        self.label_intensity = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_intensity.setObjectName("label_intensity")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_intensity)
        self.input_intensity = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.input_intensity.setObjectName("input_intensity")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.input_intensity)
        self.label_calorie_burn = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_calorie_burn.setObjectName("label_calorie_burn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_calorie_burn)
        self.input_calorie_burn = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.input_calorie_burn.setObjectName("input_calorie_burn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.input_calorie_burn)
        self.label_exercise = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_exercise.setObjectName("label_exercise")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_exercise)
        self.input_exercise = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.input_exercise.setObjectName("input_exercise")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.input_exercise)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "insert unit"))
        self.label_date.setText(_translate("Dialog", "date:"))
        self.label_duration.setText(_translate("Dialog", "duration:"))
        self.label_intensity.setText(_translate("Dialog", "intensity:"))
        self.label_calorie_burn.setText(_translate("Dialog", "calorie burn:"))
        self.label_exercise.setText(_translate("Dialog", "exercise:"))
